name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino AVR core (UNO)
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install MPU6050 library (Electronic Cats)
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "MPU6050"

      - name: Create wrapper sketch (if needed)
        run: |
          mkdir -p software/sketch
          printf '#include "../src/main.cpp"\n' > software/sketch/sketch.ino

      - name: Compile sketch (Arduino UNO)
        run: |
          # Oluşturduğumuz sketch klasörünü derliyoruz
          arduino-cli compile --fqbn arduino:avr:uno ./software/sketch
