name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino AVR core (UNO)
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # Wire çekirdekle gelir; sadece MPU6050 kur
      - name: Install MPU6050 library
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "MPU6050" || \
          arduino-cli lib install --git-url https://github.com/ElectronicCats/mpu6050
          arduino-cli lib list | grep -i mpu6050 || (echo "MPU6050 not installed" && exit 1)

      # Eğer dosyan 'software/main.ino' ise, Arduino kuralına uysun diye
      # CI içinde geçici 'software/software.ino' kopyası oluştur.
      - name: Normalize sketch name
        run: |
          if [ -f software/main.ino ] && [ ! -f software/software.ino ]; then
            cp software/main.ino software/software.ino
          fi

      - name: Compile sketch (Arduino UNO)
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./software
